export type RemoteErrorLayer =
  | 'account'
  | 'transport'
  | 'remote-agent'
  | 'workspace'
  | 'file-provider'
  | 'unknown'

export interface RemoteError {
  layer: RemoteErrorLayer
  code: string
  message: string
  retryable: boolean
  context?: Record<string, string | number | boolean | null>
}

export const REMOTE_ERROR_CODE = {
  NOT_CONFIGURED: 'REMOTE_NOT_CONFIGURED',
  LOGIN_REQUIRED: 'REMOTE_LOGIN_REQUIRED',
  TRANSPORT_UNAVAILABLE: 'REMOTE_TRANSPORT_UNAVAILABLE',
  TRANSPORT_SEND_FAILED: 'REMOTE_TRANSPORT_SEND_FAILED',
  REQUEST_CANCELLED: 'REMOTE_REQUEST_CANCELLED',
  REQUEST_TIMEOUT: 'REMOTE_REQUEST_TIMEOUT',
  PROTOCOL_INCOMPATIBLE: 'REMOTE_PROTOCOL_INCOMPATIBLE',
  UNEXPECTED_RESPONSE: 'REMOTE_UNEXPECTED_RESPONSE',
  WORKSPACE_NOT_FOUND: 'REMOTE_WORKSPACE_NOT_FOUND',
  WORKSPACE_ID_MISSING: 'REMOTE_WORKSPACE_ID_MISSING',
  CAPABILITY_PROBE_INCOMPLETE: 'REMOTE_CAPABILITY_PROBE_INCOMPLETE',
  CAPABILITY_UNAVAILABLE: 'REMOTE_CAPABILITY_UNAVAILABLE',
  FILE_FAILED: 'REMOTE_FILE_FAILED',
  FILE_TOO_LARGE: 'REMOTE_FILE_TOO_LARGE',
  FILE_READ_INCOMPLETE: 'REMOTE_FILE_READ_INCOMPLETE',
  FILE_CHANGED_DURING_READ: 'REMOTE_FILE_CHANGED_DURING_READ',
  FILE_PROTOCOL_INVALID: 'REMOTE_FILE_PROTOCOL_INVALID',
} as const
