import { mediaProjectsIpcEvents } from '../../shared/media-production/media-project-contract'
import { scheduledTasksIpcEvents } from '../../shared/scheduled-task/scheduled-task-contract'
import { webAffairsIpcEvents } from '../../shared/web-affairs/web-affair'
import { webResourcesIpcEvents } from '../../shared/web-resources/web-resource'
import { agentIpcEvents } from '../../shared/ipc/agent'
import { androidIpcEvents } from '../../shared/ipc/android'
import { authIpcEvents } from '../../shared/ipc/auth'
import { browserIpcEvents } from '../../shared/ipc/browser'
import { cclinkIpcEvents } from '../../shared/ipc/cclink'
import { editorIpcEvents } from '../../shared/ipc/editor'
import { fsIpcEvents } from '../../shared/ipc/fs'
import { terminalIpcEvents } from '../../shared/ipc/terminal'
import { windowIpcEvents } from '../../shared/ipc/window'
import { workbenchWindowIpcEvents } from '../../shared/ipc/workbench-window'
import { workspaceStateIpcEvents } from '../../shared/ipc/workspace-state'
import { updateIpcEvents } from '../../shared/update/update-contract'

export interface IpcEventFlowInventory {
  channel: string
  key: string
  owner: string
  definitionFile: string
  definitionName: string
  direction: 'main-to-renderer' | 'renderer-to-main'
  producerFiles: readonly string[]
  bridgeFiles: readonly string[]
  consumerFiles: readonly string[]
  disposerFiles: readonly string[]
  payloadBoundary: 'bounded-preload-parser' | 'bounded-main-parser' | 'no-payload'
  evidenceTerms: readonly string[]
}

interface EventInventoryGroup {
  keys: readonly string[]
  definitions: Record<string, string>
  owner: string
  definitionFile: string
  definitionName: string
  direction: IpcEventFlowInventory['direction']
  producerFiles: readonly string[]
  bridgeFiles: readonly string[]
  consumerFiles: readonly string[]
  disposerFiles?: readonly string[]
  payloadBoundary: IpcEventFlowInventory['payloadBoundary']
  evidenceTerms: readonly string[]
}

function expandEventGroup(group: EventInventoryGroup): IpcEventFlowInventory[] {
  return group.keys.map((key) => {
    const channel = group.definitions[key]
    if (!channel) throw new Error(`IPC event inventory key 未声明: ${group.definitionName}.${key}`)
    const matchingEvidenceTerms = group.evidenceTerms.filter((term) =>
      term.toLocaleLowerCase().includes(key.toLocaleLowerCase()),
    )
    return {
      channel,
      key,
      owner: group.owner,
      definitionFile: group.definitionFile,
      definitionName: group.definitionName,
      direction: group.direction,
      producerFiles: group.producerFiles,
      bridgeFiles: group.bridgeFiles,
      consumerFiles: group.consumerFiles,
      disposerFiles: group.disposerFiles ?? [...group.bridgeFiles, ...group.consumerFiles],
      payloadBoundary: group.payloadBoundary,
      evidenceTerms: matchingEvidenceTerms.length > 0 ? matchingEvidenceTerms : group.evidenceTerms,
    }
  })
}

/** 全部生产事件库存；shared 新增或删除事件时，完整性测试要求同步这里的真实 flow。 */
export const ipcEventFlowInventory: readonly IpcEventFlowInventory[] = [
  ...expandEventGroup({
    keys: ['snapshotChanged'],
    definitions: updateIpcEvents,
    owner: 'Updater',
    definitionFile: 'src/shared/update/update-contract.ts',
    definitionName: 'updateIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/ipc/updater-ipc.ts'],
    bridgeFiles: ['src/preload/renderer-support-api.ts'],
    consumerFiles: ['src/renderer/src/bootstrap/use-main-process-events.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onSnapshotChanged'],
  }),
  ...expandEventGroup({
    keys: ['sessionChanged'],
    definitions: authIpcEvents,
    owner: 'Auth',
    definitionFile: 'src/shared/ipc/auth.ts',
    definitionName: 'authIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/cclink-remote/cclink-remote-ipc.ts'],
    bridgeFiles: ['src/preload/index.ts'],
    consumerFiles: ['src/renderer/src/stores/cclink-store.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onSessionChanged'],
  }),
  ...expandEventGroup({
    keys: ['realtimeStatus', 'realtimeEvent'],
    definitions: cclinkIpcEvents,
    owner: 'CCLink Remote',
    definitionFile: 'src/shared/ipc/cclink.ts',
    definitionName: 'cclinkIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/cclink-remote/cclink-remote-ipc.ts'],
    bridgeFiles: ['src/preload/index.ts'],
    consumerFiles: ['src/renderer/src/stores/cclink-store.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onRealtimeStatus', 'onRealtimeEvent'],
  }),
  ...expandEventGroup({
    keys: ['imageUploadProgress'],
    definitions: cclinkIpcEvents,
    owner: 'CCLink Remote',
    definitionFile: 'src/shared/ipc/cclink.ts',
    definitionName: 'cclinkIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/cclink-remote/cclink-remote-ipc.ts'],
    bridgeFiles: ['src/preload/index.ts'],
    consumerFiles: ['src/renderer/src/features/cclink-remote/remote-agent-controller.tsx'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onImageUploadProgress'],
  }),
  ...expandEventGroup({
    keys: ['stream', 'complete', 'error', 'runStatus'],
    definitions: agentIpcEvents,
    owner: 'Agent',
    definitionFile: 'src/shared/ipc/agent.ts',
    definitionName: 'agentIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/agent/agent-bridge.ts'],
    bridgeFiles: ['src/preload/agent-api.ts'],
    consumerFiles: ['src/renderer/src/bootstrap/use-agent-stream-events.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onStreamEvent', 'onComplete', 'onError', 'onRunStatus'],
  }),
  ...expandEventGroup({
    keys: ['requestConfirmation'],
    definitions: agentIpcEvents,
    owner: 'Agent Permission',
    definitionFile: 'src/shared/ipc/agent.ts',
    definitionName: 'agentIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/mcp/permission.ts'],
    bridgeFiles: ['src/preload/agent-api.ts'],
    consumerFiles: ['src/renderer/src/bootstrap/use-agent-stream-events.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onRequestConfirmation'],
  }),
  ...expandEventGroup({
    keys: ['workbenchBounds'],
    definitions: browserIpcEvents,
    owner: 'Browser',
    definitionFile: 'src/shared/ipc/browser.ts',
    definitionName: 'browserIpcEvents',
    direction: 'renderer-to-main',
    producerFiles: ['src/renderer/src/components/workbench/use-workbench-bounds.ts'],
    bridgeFiles: ['src/preload/browser-api.ts'],
    consumerFiles: ['src/main/ipc/browser-ipc.ts'],
    disposerFiles: ['src/main/ipc/browser-ipc.ts'],
    payloadBoundary: 'bounded-main-parser',
    evidenceTerms: ['reportWorkbenchBounds'],
  }),
  ...expandEventGroup({
    keys: ['urlChanged', 'pageMetaChanged', 'viewStateChanged'],
    definitions: browserIpcEvents,
    owner: 'Browser',
    definitionFile: 'src/shared/ipc/browser.ts',
    definitionName: 'browserIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/browser/browser-manager.ts'],
    bridgeFiles: ['src/preload/browser-api.ts'],
    consumerFiles: ['src/renderer/src/components/workbench/use-browser-events.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onUrlChanged', 'onPageMetaChanged', 'onViewStateChanged'],
  }),
  ...expandEventGroup({
    keys: [
      'requestOpenTab',
      'popupCreated',
      'runtimeTabClosed',
      'nativeContextMenuOpened',
      'contextAgentRequest',
    ],
    definitions: browserIpcEvents,
    owner: 'Browser',
    definitionFile: 'src/shared/ipc/browser.ts',
    definitionName: 'browserIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/browser/browser-manager.ts'],
    bridgeFiles: ['src/preload/browser-api.ts'],
    consumerFiles: ['src/renderer/src/bootstrap/use-browser-open-requests.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: [
      'onRequestOpenTab',
      'onPopupCreated',
      'onRuntimeTabClosed',
      'onNativeContextMenuOpened',
      'onContextAgentRequest',
    ],
  }),
  ...expandEventGroup({
    keys: ['taskChanged', 'actionLogChanged'],
    definitions: browserIpcEvents,
    owner: 'Browser Task',
    definitionFile: 'src/shared/ipc/browser.ts',
    definitionName: 'browserIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/browser/browser-task-runtime.ts'],
    bridgeFiles: ['src/preload/browser-api.ts'],
    consumerFiles: ['src/renderer/src/components/agent-panel/AgentPanel.tsx'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onTaskChanged', 'onActionLogChanged'],
  }),
  ...expandEventGroup({
    keys: ['downloadChanged'],
    definitions: browserIpcEvents,
    owner: 'Browser Download',
    definitionFile: 'src/shared/ipc/browser.ts',
    definitionName: 'browserIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/browser/browser-download-store.ts'],
    bridgeFiles: ['src/preload/browser-api.ts'],
    consumerFiles: ['src/renderer/src/components/agent-panel/AgentPanel.tsx'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onDownloadChanged'],
  }),
  ...expandEventGroup({
    keys: ['findShortcutTriggered', 'findResult'],
    definitions: browserIpcEvents,
    owner: 'Browser Find',
    definitionFile: 'src/shared/ipc/browser.ts',
    definitionName: 'browserIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/browser/browser-manager.ts'],
    bridgeFiles: ['src/preload/browser-api.ts'],
    consumerFiles: ['src/renderer/src/features/browser/use-browser-find-bridge.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onFindShortcutTriggered', 'onFindResult'],
  }),
  ...expandEventGroup({
    keys: ['shortcutCaptureInput'],
    definitions: windowIpcEvents,
    owner: 'Window',
    definitionFile: 'src/shared/ipc/window.ts',
    definitionName: 'windowIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/ipc/window-ipc.ts'],
    bridgeFiles: ['src/preload/renderer-support-api.ts'],
    consumerFiles: ['src/renderer/src/components/settings/KeybindingsSettings.tsx'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onShortcutCaptureInput'],
  }),
  ...expandEventGroup({
    keys: ['projectionChanged'],
    definitions: workbenchWindowIpcEvents,
    owner: 'Workbench Window',
    definitionFile: 'src/shared/ipc/workbench-window.ts',
    definitionName: 'workbenchWindowIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/workbench/detachable-browser-window-controller.ts'],
    bridgeFiles: ['src/preload/index.ts', 'src/preload/auxiliary.ts'],
    consumerFiles: ['src/renderer/src/components/workbench/AuxiliaryBrowserLayout.tsx'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onProjectionChanged'],
  }),
  ...expandEventGroup({
    keys: ['placementChanged'],
    definitions: workbenchWindowIpcEvents,
    owner: 'Workbench Window',
    definitionFile: 'src/shared/ipc/workbench-window.ts',
    definitionName: 'workbenchWindowIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/workbench/detachable-browser-window-controller.ts'],
    bridgeFiles: ['src/preload/index.ts', 'src/preload/auxiliary.ts'],
    consumerFiles: ['src/renderer/src/bootstrap/use-workbench-window-events.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onPlacementChanged'],
  }),
  ...expandEventGroup({
    keys: ['tabDetachReleased'],
    definitions: workbenchWindowIpcEvents,
    owner: 'Workbench Window',
    definitionFile: 'src/shared/ipc/workbench-window.ts',
    definitionName: 'workbenchWindowIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/workbench/detachable-browser-window-controller.ts'],
    bridgeFiles: ['src/preload/index.ts'],
    consumerFiles: ['src/renderer/src/components/workbench/Workbench.tsx'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onTabDetachReleased'],
  }),
  ...expandEventGroup({
    keys: ['changed'],
    definitions: scheduledTasksIpcEvents,
    owner: 'Scheduled Tasks',
    definitionFile: 'src/shared/scheduled-task/scheduled-task-contract.ts',
    definitionName: 'scheduledTasksIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/scheduled-task/scheduled-task-ipc.ts'],
    bridgeFiles: ['src/preload/index.ts'],
    consumerFiles: ['src/renderer/src/features/scheduled-tasks/ScheduledTasksSidebar.tsx'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onChanged'],
  }),
  ...expandEventGroup({
    keys: ['changed'],
    definitions: mediaProjectsIpcEvents,
    owner: 'Media Projects',
    definitionFile: 'src/shared/media-production/media-project-contract.ts',
    definitionName: 'mediaProjectsIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/media-production/media-project-ipc.ts'],
    bridgeFiles: ['src/preload/index.ts'],
    consumerFiles: ['src/renderer/src/features/media-production/PromotionalVideoSidebar.tsx'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onChanged'],
  }),
  ...expandEventGroup({
    keys: ['changed'],
    definitions: webAffairsIpcEvents,
    owner: 'Web Affairs',
    definitionFile: 'src/shared/web-affairs/web-affair.ts',
    definitionName: 'webAffairsIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/runtime/core-services.ts'],
    bridgeFiles: ['src/preload/web-affairs-api.ts'],
    consumerFiles: ['src/renderer/src/features/web-affairs/WebAffairsSidebar.tsx'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onChanged'],
  }),
  ...expandEventGroup({
    keys: ['agentLaunchRequested'],
    definitions: webResourcesIpcEvents,
    owner: 'Web Resources',
    definitionFile: 'src/shared/web-resources/web-resource.ts',
    definitionName: 'webResourcesIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/web-resources/agent-web-resource-launch-coordinator.ts'],
    bridgeFiles: ['src/preload/web-resources-api.ts'],
    consumerFiles: ['src/renderer/src/bootstrap/use-agent-web-resource-launch-requests.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onAgentLaunchRequest'],
  }),
  ...expandEventGroup({
    keys: ['agentLaunchAcknowledged'],
    definitions: webResourcesIpcEvents,
    owner: 'Web Resources',
    definitionFile: 'src/shared/web-resources/web-resource.ts',
    definitionName: 'webResourcesIpcEvents',
    direction: 'renderer-to-main',
    producerFiles: ['src/renderer/src/bootstrap/use-agent-web-resource-launch-requests.ts'],
    bridgeFiles: ['src/preload/web-resources-api.ts'],
    consumerFiles: ['src/main/web-resources/agent-web-resource-launch-coordinator.ts'],
    disposerFiles: ['src/main/web-resources/agent-web-resource-launch-coordinator.ts'],
    payloadBoundary: 'bounded-main-parser',
    evidenceTerms: ['acknowledgeAgentLaunch'],
  }),
  ...expandEventGroup({
    keys: ['watchDirChanged'],
    definitions: fsIpcEvents,
    owner: 'Filesystem',
    definitionFile: 'src/shared/ipc/fs.ts',
    definitionName: 'fsIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/fs/fs-ipc.ts'],
    bridgeFiles: ['src/preload/fs-api.ts'],
    consumerFiles: ['src/renderer/src/components/sidebar/FileTree.tsx'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['watchDir'],
  }),
  ...expandEventGroup({
    keys: ['requestCommandConfirmation'],
    definitions: terminalIpcEvents,
    owner: 'Terminal',
    definitionFile: 'src/shared/ipc/terminal.ts',
    definitionName: 'terminalIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/terminal/terminal-confirmation-service.ts'],
    bridgeFiles: ['src/preload/index.ts'],
    consumerFiles: ['src/renderer/src/bootstrap/use-terminal-events.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onRequestCommandConfirmation'],
  }),
  ...expandEventGroup({
    keys: ['executionEvent'],
    definitions: terminalIpcEvents,
    owner: 'Terminal',
    definitionFile: 'src/shared/ipc/terminal.ts',
    definitionName: 'terminalIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/ipc/terminal-ipc.ts'],
    bridgeFiles: ['src/preload/index.ts'],
    consumerFiles: ['src/renderer/src/bootstrap/use-terminal-events.ts'],
    disposerFiles: [
      'src/main/ipc/terminal-ipc.ts',
      'src/renderer/src/bootstrap/use-terminal-events.ts',
    ],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onExecutionEvent', 'unsubscribe'],
  }),
  ...expandEventGroup({
    keys: ['storeInstallProgress'],
    definitions: androidIpcEvents,
    owner: 'Android',
    definitionFile: 'src/shared/ipc/android.ts',
    definitionName: 'androidIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/ipc/android-ipc.ts'],
    bridgeFiles: ['src/preload/android-api.ts'],
    consumerFiles: ['src/renderer/src/bootstrap/use-main-process-events.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onStoreInstallProgress'],
  }),
  ...expandEventGroup({
    keys: ['touch'],
    definitions: androidIpcEvents,
    owner: 'Android/Scrcpy',
    definitionFile: 'src/shared/ipc/android.ts',
    definitionName: 'androidIpcEvents',
    direction: 'renderer-to-main',
    producerFiles: ['src/renderer/src/components/workbench/AndroidDisplay.tsx'],
    bridgeFiles: ['src/preload/android-api.ts'],
    consumerFiles: ['src/main/ipc/android-ipc.ts'],
    disposerFiles: ['src/main/ipc/android-ipc.ts'],
    payloadBoundary: 'bounded-main-parser',
    evidenceTerms: ['sendTouch'],
  }),
  ...expandEventGroup({
    keys: ['videoFrame', 'mirrorError'],
    definitions: androidIpcEvents,
    owner: 'Android/Scrcpy',
    definitionFile: 'src/shared/ipc/android.ts',
    definitionName: 'androidIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/android/scrcpy-bridge.ts'],
    bridgeFiles: ['src/preload/android-api.ts'],
    consumerFiles: ['src/renderer/src/components/workbench/AndroidDisplay.tsx'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onVideoFrame', 'onMirrorError'],
  }),
  ...expandEventGroup({
    keys: ['mirrorDisconnected'],
    definitions: androidIpcEvents,
    owner: 'Android/Scrcpy',
    definitionFile: 'src/shared/ipc/android.ts',
    definitionName: 'androidIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/android/scrcpy-bridge.ts'],
    bridgeFiles: ['src/preload/android-api.ts'],
    consumerFiles: ['src/renderer/src/components/workbench/AndroidDisplay.tsx'],
    payloadBoundary: 'no-payload',
    evidenceTerms: ['onMirrorDisconnected'],
  }),
  ...expandEventGroup({
    keys: ['readRequest', 'saveRequest'],
    definitions: editorIpcEvents,
    owner: 'Editor',
    definitionFile: 'src/shared/ipc/editor.ts',
    definitionName: 'editorIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/mcp/modules/editor/index.ts'],
    bridgeFiles: ['src/preload/renderer-support-api.ts'],
    consumerFiles: [
      'src/renderer/src/components/workbench/MarkdownEditor.tsx',
      'src/renderer/src/components/workbench/SourceTextEditor.tsx',
    ],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onReadRequest', 'onSaveRequest'],
  }),
  ...expandEventGroup({
    keys: ['flushRequest'],
    definitions: workspaceStateIpcEvents,
    owner: 'Workspace State',
    definitionFile: 'src/shared/ipc/workspace-state.ts',
    definitionName: 'workspaceStateIpcEvents',
    direction: 'main-to-renderer',
    producerFiles: ['src/main/workspace/renderer-workspace-state-flush.ts'],
    bridgeFiles: ['src/preload/local-ops-api.ts'],
    consumerFiles: ['src/renderer/src/bootstrap/use-workspace-state-flush.ts'],
    payloadBoundary: 'bounded-preload-parser',
    evidenceTerms: ['onFlushRequest'],
  }),
  ...expandEventGroup({
    keys: ['flushAcknowledged'],
    definitions: workspaceStateIpcEvents,
    owner: 'Workspace State',
    definitionFile: 'src/shared/ipc/workspace-state.ts',
    definitionName: 'workspaceStateIpcEvents',
    direction: 'renderer-to-main',
    producerFiles: ['src/renderer/src/bootstrap/use-workspace-state-flush.ts'],
    bridgeFiles: ['src/preload/local-ops-api.ts'],
    consumerFiles: ['src/main/workspace/renderer-workspace-state-flush.ts'],
    disposerFiles: ['src/main/workspace/renderer-workspace-state-flush.ts'],
    payloadBoundary: 'bounded-main-parser',
    evidenceTerms: ['acknowledgeFlush'],
  }),
]
